language: python

python:
- 2.7
services: postgresql

env:
  global:
  - DJANGO_SETTINGS_MODULE="mango_core.settings"
  - PYTHONPATH="/home/travis/build/mango-app/mango-core"
  - PIP_USE_MIRRORS=true
  - DATABASE_URL="postgres://postgres:@127.0.0.1:5432/travisdb"
  - DJANGO_SECRET_KEY="jyghqie2a+r_m9wp02w%9h6#*y+5$)13ap!a6jxv^7j43e#kth&g6+35-"

install:
- pip install -r requirements.txt
- pip install coveralls

before_script:
- psql -c "CREATE DATABASE travisdb;" -U postgres

script:
- python manage.py migrate --noinput
- python manage.py makemigrations mango_core_common --noinput
- python manage.py migrate --noinput
- coverage run --source=mango_core manage.py test

after_success:
- pip freeze
- echo Uploading code coverage data ...; coveralls

deploy:
  provider: heroku
  api_key:
    secure: FUacbQe+qNp1HMs4RjaWpQzaXTJ+Vs9cPLI9axs5jrIJgsoHZ8xrSOqusYsurVuRS6Op7x3ya8EyGDy2Eveth8HZ37dCWscARyNjl9TgXP6/lEpYxyQM0BB6Ry7UG+KvSmvfOxRph6PAJ6BT3nCTKDpydWMRyT1G+Tht4slEBw4cgBg12kOF6LlEs+o1JvzZQVOij4gWU8bFWMXTId3NIlAfuvVOkY07xq1bKoh4tyukyGQ4dD0HZwV/onHuRHPKJ62xzWdiSzLADGnj5KuAMEFV7mKszqh620l0LyHMR76IAYaWZ+go+I+Zqd4MHky0FBPpFx4ZT0ClKkJbnMctzYoH+0/F/QptgtgGcAmJGcHInjIBLlv4rnl+s2Zxu93O4sA8lAMy9HHylO9X0s3edTIjmUn6S7+BLi0vXGBB2uvCuZmSDN9WfDKVljEokfwZAUeHVjQq3bhBuRGF/eV1n616sdC7XmgFuvdwoHFfHtgDw3ragqe0irWKsvaftGSrtEkHBon7UiFgBS1IL14ZZOjDGmGdkS6bzqbOhiMrfanRtgfiqMoavXR2h4FDLT7h0/7NYNUqgyhrXa8pqkGm1Chib6Wq7HsvS2vTiYrWjjaER8b+2INYqopx7fvSlhoQw1ERu/Tt2/89gIROtOUrjREZcS7cmRXaWkKUJdY/mQk=
